import java.time.LocalDate
pipeline{
	agent any
	stages{
		stage("holaMundo"){
			steps{
				script{
					println("[A Coruña               A Coruña, Alacant               Alacant, Albacete               Albacete, Almería               Almería, Araba               Araba, Asturias               Asturias, Badajoz     Badajoz, Barcelona               Barcelona, Bizkaia               Bizkaia, Burgos               Burgos, Cantabria               Cantabria"])
				}
			}
		}
	}
}
